source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'NEKit_Example' do
  pod 'NEKit', :path => '../'

  target 'NEKit_Tests' do
    inherit! :search_paths

    
  end
end
